### ISSUE TITLE
Add "Videos" as supported platform

### ISSUE THREAD

**Issue by MacDhughaill** [MayeulC/hb-downloader#13]
I discovered that in addition to the familiar "games, ebooks, audio" platforms, there is now a "video" platform. By default, `hb-downloader` does not list or download anything from the video platform. A simple change like below to `hb-downloader-settings.yaml` does successfully download the videos when a plain command of `hb-downloader.py download` is ran, though, so it seems support should be easy to add?

````
download-platforms:
  audio: True
  ebook: True
  windows: True
  mac: True
  linux: True
  android: True
  asmjs: False
  video: True
````
